name: Build macOS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipreqs and generate requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pipreqs . --force

      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt

      - name: Build .app bundle with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --windowed --name MijnApp app.py

      - name: Create DMG from .app
        run: |
          hdiutil create -volname "MijnApp" -srcfolder "dist/MijnApp.app" -ov -format UDZO MijnApp.dmg

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: MijnApp-app
          path: dist/MijnApp.app

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: MijnApp-dmg
          path: MijnApp.dmg
