name: Build macOS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build app with PyInstaller
        run: |
          pyinstaller --onefile --windowed app.py

      - name: Create DMG
        run: |
          mkdir dmg_temp
          cp dist/app dmg_temp/
          hdiutil create -volname "MijnApp" -srcfolder dmg_temp -ov -format UDZO MijnApp.dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: MijnApp-dmg
          path: MijnApp.dmg
