name: Build macOS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Detect Python file
        id: detect_py
        run: |
          FILE=$(find . -maxdepth 1 -name "*.py" | head -n 1)
          BASENAME=$(basename "$FILE" .py)
          echo "PY_FILE=$FILE" >> $GITHUB_OUTPUT
          echo "BASENAME=$BASENAME" >> $GITHUB_OUTPUT

      - name: Install pipreqs and generate requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pipreqs . --force

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Install ImageMagick
        run: brew install imagemagick

      - name: Prepare iconset folder and convert icon.ico to icon.icns
        run: |
          if [ ! -f icon/icon.ico ]; then
            echo "icon.ico not found in icon/ folder, skipping icon conversion"
            exit 1
          fi
          mkdir -p iconset
          magick icon/icon.ico -resize 16x16     iconset/icon_16x16.png
          magick icon/icon.ico -resize 32x32     iconset/icon_16x16@2x.png
          magick icon/icon.ico -resize 32x32     iconset/icon_32x32.png
          magick icon/icon.ico -resize 64x64     iconset/icon_32x32@2x.png
          magick icon/icon.ico -resize 128x128   iconset/icon_128x128.png
          magick icon/icon.ico -resize 256x256   iconset/icon_128x128@2x.png
          magick icon/icon.ico -resize 256x256   iconset/icon_256x256.png
          magick icon/icon.ico -resize 512x512   iconset/icon_256x256@2x.png
          magick icon/icon.ico -resize 512x512   iconset/icon_512x512.png
          magick icon/icon.ico -resize 1024x1024 iconset/icon_512x512@2x.png

          iconutil -c icns iconset -o icon/icon.icns

      - name: Build .app bundle with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --windowed --name "${{ steps.detect_py.outputs.BASENAME }}" --icon=icon/icon.icns "${{ steps.detect_py.outputs.PY_FILE }}"

      - name: Create DMG from .app
        run: |
          hdiutil create -volname "${{ steps.detect_py.outputs.BASENAME }}" -srcfolder "dist/${{ steps.detect_py.outputs.BASENAME }}.app" -ov -format UDZO "${{ steps.detect_py.outputs.BASENAME }}.dmg"

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.detect_py.outputs.BASENAME }}-app
          path: dist/${{ steps.detect_py.outputs.BASENAME }}.app

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.detect_py.outputs.BASENAME }}-dmg
          path: ${{ steps.detect_py.outputs.BASENAME }}.dmg
