name: Build macOS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Detect Python file
        id: detect_py
        run: |
          FILE=$(find . -maxdepth 1 -name "*.py" | head -n 1)
          BASENAME=$(basename "$FILE" .py)
          echo "PY_FILE=$FILE" >> $GITHUB_OUTPUT
          echo "BASENAME=$BASENAME" >> $GITHUB_OUTPUT

      - name: Install pipreqs and generate requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pipreqs . --force

      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt

      - name: Install ImageMagick (for .ico conversion)
        run: |
          brew install imagemagick

      - name: Convert .ico to .icns
        run: |
          mkdir -p iconset

          for size in 16 32 64 128 256 512; do
            magick icon/icon.ico -resize ${size}x${size} iconset/icon_${size}x${size}.png
          done

          # Kopieer juiste formaten naar iconset met correcte namen
          cp -f iconset/icon_16x16.png       iconset/icon_16x16.png
          cp -f iconset/icon_32x32.png       iconset/icon_16x16@2x.png
          cp -f iconset/icon_32x32.png       iconset/icon_32x32.png
          cp -f iconset/icon_64x64.png       iconset/icon_32x32@2x.png
          cp -f iconset/icon_128x128.png     iconset/icon_128x128.png
          cp -f iconset/icon_256x256.png     iconset/icon_128x128@2x.png
          cp -f iconset/icon_256x256.png     iconset/icon_256x256.png
          cp -f iconset/icon_512x512.png     iconset/icon_256x256@2x.png
          cp -f iconset/icon_512x512.png     iconset/icon_512x512.png
          cp -f iconset/icon_512x512.png     iconset/icon_512x512@2x.png

          iconutil -c icns iconset -o icon/icon.icns

      - name: Build .app bundle with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --windowed \
                      --icon=icon/icon.icns \
                      --name "${{ steps.detect_py.outputs.BASENAME }}" \
                      "${{ steps.detect_py.outputs.PY_FILE }}"

      - name: Create DMG from .app
        run: |
          hdiutil create -volname "${{ steps.detect_py.outputs.BASENAME }}" \
                         -srcfolder "dist/${{ steps.detect_py.outputs.BASENAME }}.app" \
                         -ov -format UDZO "${{ steps.detect_py.outputs.BASENAME }}.dmg"

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.detect_py.outputs.BASENAME }}-app
          path: dist/${{ steps.detect_py.outputs.BASENAME }}.app

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.detect_py.outputs.BASENAME }}-dmg
          path: ${{ steps.detect_py.outputs.BASENAME }}.dmg
